theme: minima
title: Abhinav's Website
author: Abhinav Jha
email: jhaabhinav@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal website licensed under MIT License.
  This site is hosted at Github Pages and created with Jekyll, Vim and vigour. 
  
# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
show_excerpts: false # set to false to remove excerpts on the homepage

plugins:
  - jekyll-feed
